---
- name: Create /opt/devops directory and add info.txt
  hosts: all
  become: yes   # run with sudo privileges
  tasks:
    - name: Ensure /opt/devops directory exists
      file:
        path: /opt/devops
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Create info.txt with content
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible!\n"
        owner: ec2-user
        group: ec2-user
        mode: '0644'
...
