---
- name: Ensure /opt/devops directory exists
  hosts: all
  become: true
  tasks:
    - name: Create /opt/devops directory
      file:
        path: /opt/devops
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Verify directory exists
      command: ls -ld /opt/devops
      register: dir_check

    - name: Show directory details
      debug:
        var: dir_check.stdout
...
