---
- name: Install git and httpd on all
  hosts: all
  become: yes  # Run as sudo

  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
...
