---
- name: Install HTTP server
  hosts: g1
  become: yes   # run with sudo privileges

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start httpd
      service:
        name: httpd
        state: started
    
    - name: Enable httpd
      service:
        name: httpd
        enabled: yes
...
