---
- name: Install apache on ub1
  hosts: ub1
  become: yes  # Run as sudo

  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: start apache2
      service:
        name: apache2
        state: started

    - name: Enable apache2
      service:
        name: apache2
        enabled: yes
...
